# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-11 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default=datetime.datetime(2019, 3, 11, 11, 11, 58, 195629, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
